**Table of contents**<a id='toc0_'></a>    
- [Proyecto SARIMA - Análisis de Serie de Tiempo](#toc1_)    
  - [📚 Importación de librerías](#toc1_1_)    
  - [💾 Descarga de la serie de tiempo](#toc1_2_)    
    - [📨 Get from API](#toc1_2_1_)    
  - [🔎Exporacion de la Serie](#toc1_3_)    
    - [🗓️ Historico de la Serie](#toc1_3_1_)    
      - [✂️ Corte de 2021 - actualidad](#toc1_3_1_1_)    
    - [🎉 Serie con sustitucion de dias festivos y fines de semana por valor anterior](#toc1_3_2_)    
      - [✂️ Corte de 2021 - actualidad](#toc1_3_2_1_)    
  - [➗ Division Train/Test](#toc1_4_)    
  - [📈 Pruebas de estacionariedad](#toc1_5_)    
  - [📏 Auto-diferenciación](#toc1_6_)    
  - [🪛 Descomposicion STL](#toc1_7_)    
  - [🎭 Pruebas ACF y PACF](#toc1_8_)    
  - [💻 Modelado SARIMA](#toc1_9_)    
  - [🟰 Metricas](#toc1_10_)    
  - [🎯 Conclusiones](#toc1_11_)    

<!-- vscode-jupyter-toc-config
	numbering=false
	anchor=true
	flat=false
	minLevel=1
	maxLevel=6
	/vscode-jupyter-toc-config -->
<!-- THIS CELL WILL BE REPLACED ON TOC UPDATE. DO NOT WRITE YOUR TEXT IN THIS CELL -->

# <a id='toc1_'></a>[Proyecto SARIMA - Análisis de Serie de Tiempo](#toc0_)

Este notebook tiene como objetivo realizar el análisis y modelado de una serie de tiempo utilizando un modelo **SARIMA**.
Las secciones están predefinidas para facilitar el trabajo colaborativo durante el examen.  

----

## <a id='toc1_1_'></a>[📚 Importación de librerías](#toc0_)
En esta sección se importarán todas las librerías necesarias para el proyecto.

In [ ]:
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

import plotly.graph_objects as go
import pandas as pd
from pandas.tseries.offsets import BDay

import pandas as pd
import numpy as np
from datetime import datetime

from statsmodels.tsa.stattools import adfuller, kpss
from statsmodels.tsa.seasonal import STL
from statsmodels.tsa.stattools import acf, pacf
from statsmodels.tsa.statespace.sarimax import SARIMAX

from scipy.stats import boxcox
from scipy.special import inv_boxcox

from sklearn.metrics import mean_squared_error, mean_absolute_error
import pandas as pd
from statsmodels.tsa.statespace.sarimax import SARIMAX
from pandas.tseries.offsets import BDay

import warnings
warnings.filterwarnings('ignore')

## <a id='toc1_2_'></a>[💾 Descarga de la serie de tiempo](#toc0_)
En esta sección se descargará la serie de tiempo desde la fuente correspondiente y se visualizará su estructura inicial.

### <a id='toc1_2_1_'></a>[📨 Get from API](#toc0_)

In [69]:
'''
# Leer el token desde el archivo .secrets
with open(".secrets", "r") as f:
    token = f.read().strip()

'''

'\n# Leer el token desde el archivo .secrets\nwith open(".secrets", "r") as f:\n    token = f.read().strip()\n\n'

In [70]:
'''

# Endpoint para la serie SF43718 (Tipo de cambio FIX)
url = "https://www.banxico.org.mx/SieAPIRest/service/v1/series/SF43718/datos"

# Encabezados con el token
headers = {
    "Bmx-Token": token
}

# Hacemos la petición
response = requests.get(url, headers=headers)

if response.status_code == 200:
    data = response.json()
    serie = data["bmx"]["series"][0]["datos"]

    # Convertir a DataFrame
    df = pd.DataFrame(serie)
    df.rename(columns={"fecha": "Fecha", "dato": "TipoCambio"}, inplace=True)

    # Convertir columnas
    df["Fecha"] = pd.to_datetime(df["Fecha"], format="%d/%m/%Y")
    df["TipoCambio"] = pd.to_numeric(df["TipoCambio"], errors="coerce")

    # Crear carpeta data si no existe
    os.makedirs("data", exist_ok=True)

    # Guardar en CSV
    csv_path = "data/tipo_cambio_fix.csv"
    df.to_csv(csv_path, index=False, encoding="utf-8-sig")
    print(f"Datos guardados en {csv_path}")

    # Graficar con Plotly
    fig = px.line(df, x="Fecha", y="TipoCambio",
                  title="Tipo de cambio FIX (Peso/Dólar) - Banxico",
                  labels={"TipoCambio": "Pesos por USD"})
    fig.show()

else:
    print("Error en la consulta:", response.status_code, response.text)

'''

'\n\n# Endpoint para la serie SF43718 (Tipo de cambio FIX)\nurl = "https://www.banxico.org.mx/SieAPIRest/service/v1/series/SF43718/datos"\n\n# Encabezados con el token\nheaders = {\n    "Bmx-Token": token\n}\n\n# Hacemos la petición\nresponse = requests.get(url, headers=headers)\n\nif response.status_code == 200:\n    data = response.json()\n    serie = data["bmx"]["series"][0]["datos"]\n\n    # Convertir a DataFrame\n    df = pd.DataFrame(serie)\n    df.rename(columns={"fecha": "Fecha", "dato": "TipoCambio"}, inplace=True)\n\n    # Convertir columnas\n    df["Fecha"] = pd.to_datetime(df["Fecha"], format="%d/%m/%Y")\n    df["TipoCambio"] = pd.to_numeric(df["TipoCambio"], errors="coerce")\n\n    # Crear carpeta data si no existe\n    os.makedirs("data", exist_ok=True)\n\n    # Guardar en CSV\n    csv_path = "data/tipo_cambio_fix.csv"\n    df.to_csv(csv_path, index=False, encoding="utf-8-sig")\n    print(f"Datos guardados en {csv_path}")\n\n    # Graficar con Plotly\n    fig = px.line(df, x="Fecha", y="TipoCambio",\n                  title="Tipo de cambio FIX (Peso/Dólar) - Banxico",\n                  labels={"TipoCambio": "Pesos por USD"})\n    fig.show()\n\nelse:\n    print("Error en la consulta:", response.status_code, response.text)\n\n'

## <a id='toc1_3_'></a>[🔎Exporacion de la Serie](#toc0_)

### <a id='toc1_3_1_'></a>[🗓️ Historico de la Serie](#toc0_)

In [71]:
df_Ori = pd.read_csv("data/tipo_cambio_fix.csv")
df_Ori.set_index('Fecha', inplace=True) 
df_Ori.head()

            TipoCambio
Fecha
1991-11-12      3.0735
1991-11-13      3.0712
1991-11-14      3.0718
1991-11-15      3.0684
1991-11-18      3.0673

In [72]:
print(df_Ori.index.dtype)       
print(df_Ori.shape)
print(df_Ori.head(3))
print(df_Ori.tail(3))

object
(8508, 1)
            TipoCambio
Fecha
1991-11-12      3.0735
1991-11-13      3.0712
1991-11-14      3.0718
            TipoCambio
Fecha
2025-09-12     18.4757
2025-09-15     18.3635
2025-09-17     18.3257

In [73]:
fig = px.line(
    df_Ori,
    x=df_Ori.index,
    y="TipoCambio",
    title="Tipo de cambio FIX (Peso/Dólar) - Banxico",
    labels={"TipoCambio": "Pesos por USD"}
)

fig.show()

#### <a id='toc1_3_1_1_'></a>[✂️ Corte de 2021 - actualidad](#toc0_)

In [74]:
fecha_inicio = datetime(2021, 1, 1)
hoy = datetime.today()

dias = (hoy - fecha_inicio).days
print(f"Días entre 2021-01-01 y hoy: {dias}")

# Asegúrate de que el índice sea datetime
df_Ori.index = pd.to_datetime(df_Ori.index)

# Filtrar desde 2021-01-01 hasta hoy
fecha_inicio = "2021-01-01"
hoy = pd.Timestamp.today()

df_Ori = df_Ori.loc[fecha_inicio:hoy]

# Graficar con Plotly
fig = px.line(
    df_Ori,
    x=df_Ori.index,
    y="TipoCambio",
    title="Tipo de cambio FIX (Peso/Dólar) - Banxico",
    labels={"TipoCambio": "Pesos por USD"}
)

# Mostrar gráfico interactivo
fig.show()

Días entre 2021-01-01 y hoy: 1725

### <a id='toc1_3_2_'></a>[🎉 Serie con sustitucion de dias festivos y fines de semana por valor anterior](#toc0_)

In [75]:

df = pd.read_csv("data/tipo_cambio_fix.csv", parse_dates=["Fecha"])
df = df.set_index('Fecha').sort_index()

# Asegura índice datetime válido
df.index = pd.to_datetime(df.index, errors='coerce')
df = df[~df.index.isna()]

# === CLAVE: trabajar en frecuencia de días hábiles (B), sin inventar fines de semana ===
# asfreq('B') crea huecos solo en días hábiles; ffill rellena feriados hábiles si faltan
df = df.asfreq('B').ffill()
df.index.name = 'Fecha'

In [76]:
print(df.index.dtype)        
print(df.shape)
print(df.head(3))
print(df.tail(3))

datetime64[ns]
(8832, 1)
            TipoCambio
Fecha
1991-11-12      3.0735
1991-11-13      3.0712
1991-11-14      3.0718
            TipoCambio
Fecha
2025-09-15     18.3635
2025-09-16     18.3635
2025-09-17     18.3257

In [77]:
# Graficar con Plotly
fig = px.line(
    df,
    x=df.index,
    y="TipoCambio",
    title="Tipo de cambio FIX (Peso/Dólar) - Banxico",
    labels={"TipoCambio": "Pesos por USD"}
)

# Mostrar gráfico interactivo
fig.show()

#### <a id='toc1_3_2_1_'></a>[✂️ Corte de 2021 - actualidad](#toc0_)

In [78]:
import pandas as pd
from datetime import datetime

fecha_inicio = datetime(2021, 1, 1)
hoy = datetime.today()

dias = (hoy - fecha_inicio).days
print(f"Días entre 2021-01-01 y hoy: {dias}")

# Asegúrate de que el índice sea datetime
df.index = pd.to_datetime(df.index)

# Filtrar desde 2021-01-01 hasta hoy
fecha_inicio = "2021-01-01"
hoy = pd.Timestamp.today()

df = df.loc[fecha_inicio:hoy]

# Graficar con Plotly
fig = px.line(
    df,
    x=df.index,
    y="TipoCambio",
    title="Tipo de cambio FIX (Peso/Dólar) - Banxico",
    labels={"TipoCambio": "Pesos por USD"}
)

# Mostrar gráfico interactivo
fig.show()

Días entre 2021-01-01 y hoy: 1725

## <a id='toc1_4_'></a>[➗ Division Train/Test](#toc0_)

In [79]:
df_train = df[:-12]
df_test = df[-12:]

display(df_train)
display(df_test)

            TipoCambio
Fecha
2021-01-01     19.9087
2021-01-04     19.8457
2021-01-05     19.9437
2021-01-06     19.7250
2021-01-07     19.9100
...                ...
2025-08-26     18.6843
2025-08-27     18.6912
2025-08-28     18.6522
2025-08-29     18.6440
2025-09-01     18.6460

[1217 rows x 1 columns]

            TipoCambio
Fecha
2025-09-02     18.7072
2025-09-03     18.6873
2025-09-04     18.7577
2025-09-05     18.6792
2025-09-08     18.6550
2025-09-09     18.6353
2025-09-10     18.5920
2025-09-11     18.5287
2025-09-12     18.4757
2025-09-15     18.3635
2025-09-16     18.3635
2025-09-17     18.3257

## <a id='toc1_5_'></a>[📈 Pruebas de estacionariedad](#toc0_)
Esta sección incluye funciones para verificar si la serie es estacionaria.

**Pruebas incluidas:**
- Prueba ADF (Augmented Dickey-Fuller)
- Prueba KPSS (Kwiatkowski–Phillips–Schmidt–Shin)

La función devolverá un diagnóstico con base en los valores p.

In [80]:
def adf_test(series):
    result = adfuller(series)
    p_value = result[1]
    print(f"ADF Statistic: {result[0]:.4f}, p-value: {p_value:.4f}")
    return p_value < 0.05  # Si es menor a 0.05, la serie es estacionaria

def kpss_test(series):
    result = kpss(series, regression='c')
    p_value = result[1]
    print(f"KPSS Statistic: {result[0]:.4f}, p-value: {p_value:.4f}")
    return p_value > 0.05  # Si es mayor a 0.05, la serie es estacionaria

def check_stationarity(series):
    print('--- Prueba ADF ---')
    adf_result = adf_test(series)
    print('\n--- Prueba KPSS ---')
    kpss_result = kpss_test(series)

    if adf_result and kpss_result:
        print('\nConclusión: La serie es estacionaria.')
        return True
    else:
        print('\nConclusión: La serie NO es estacionaria.')
        return False

In [81]:
check_stationarity(df_train)

--- Prueba ADF ---
ADF Statistic: -1.7580, p-value: 0.4015

--- Prueba KPSS ---
KPSS Statistic: 1.8636, p-value: 0.0100

Conclusión: La serie NO es estacionaria.

False

## <a id='toc1_6_'></a>[📏 Auto-diferenciación](#toc0_)
En esta sección se aplicarán diferenciaciones automáticas hasta lograr que la serie sea estacionaria.

In [82]:
def auto_difference(series, max_diff=5):
    diff_count = 0
    temp_series = series.copy()

    while not check_stationarity(temp_series) and diff_count < max_diff:
        temp_series = temp_series.diff().dropna()
        diff_count += 1
        print(f"Aplicando diferenciación #{diff_count}")

    print(f"Número total de diferenciaciones aplicadas: {diff_count}")
    return temp_series, diff_count

In [83]:
df_diff, count = auto_difference(df_train)

--- Prueba ADF ---
ADF Statistic: -1.7580, p-value: 0.4015

--- Prueba KPSS ---
KPSS Statistic: 1.8636, p-value: 0.0100

Conclusión: La serie NO es estacionaria.
Aplicando diferenciación #1
--- Prueba ADF ---
ADF Statistic: -12.8543, p-value: 0.0000

--- Prueba KPSS ---
KPSS Statistic: 0.0699, p-value: 0.1000

Conclusión: La serie es estacionaria.
Número total de diferenciaciones aplicadas: 1

## <a id='toc1_7_'></a>[🪛 Descomposicion STL](#toc0_)
para la posteridad

In [84]:
# Chunk 14 (AJUSTAR)
TARGET_COL = 'TipoCambio'
PERIOD     = 5      # semana hábil
ROBUST     = True
SHOW_RANGESLIDER = True

In [85]:
df = df_train.copy()
if not isinstance(df.index, pd.DatetimeIndex):
    df.index = pd.to_datetime(df.index, errors='raise')
df = df.sort_index()
if df.index.duplicated().any():
    df = df.groupby(level=0)[TARGET_COL].mean().to_frame()
if TARGET_COL not in df.columns:
    raise ValueError(f"No encuentro la columna '{TARGET_COL}' en df_train.")
y = df[TARGET_COL].astype(float).copy()
if y.isna().any():
    y = y.interpolate(method='time').ffill().bfill()


if PERIOD is None:
    freq = pd.infer_freq(y.index)
    if freq in ('D', 'B'): PERIOD = 7
    elif freq in ('H',): PERIOD = 24
    elif freq in ('W','W-SUN','W-MON','W-TUE','W-WED','W-THU','W-FRI','W-SAT'): PERIOD = 52
    elif freq in ('MS','M','ME'): PERIOD = 12
    elif freq in ('QS','Q','QE'): PERIOD = 4
    elif freq in ('AS','A','Y'): PERIOD = 1
    else:
        PERIOD = 7
        print("No pude inferir frecuencia; usando PERIOD=7 por defecto. Ajusta si aplica otra estacionalidad.")


stl = STL(y, period=PERIOD, robust=ROBUST)
res = stl.fit()


df_stl = pd.DataFrame({
    'observado': y,
    'tendencia': res.trend,
    'estacional': res.seasonal,
    'residuo': res.resid
}, index=y.index)

In [86]:
fig = make_subplots(
    rows=2, cols=2, shared_xaxes=False,
    subplot_titles=("Observado", "Tendencia (STL)", "Estacionalidad (STL)", "Residuo (STL)")
)

fig.add_trace(go.Scatter(x=df_stl.index, y=df_stl['observado'],  mode='lines', name='Observado'), row=1, col=1)
fig.add_trace(go.Scatter(x=df_stl.index, y=df_stl['tendencia'],  mode='lines', name='Tendencia'), row=1, col=2)
fig.add_trace(go.Scatter(x=df_stl.index, y=df_stl['estacional'], mode='lines', name='Estacional'), row=2, col=1)
fig.add_trace(go.Scatter(x=df_stl.index, y=df_stl['residuo'],    mode='lines', name='Residuo'),   row=2, col=2)

fig.update_xaxes(matches='x')  

if SHOW_RANGESLIDER:
    fig.update_xaxes(rangeslider=dict(visible=True), row=2, col=1)
    fig.update_xaxes(rangeselector=dict(
        buttons=[
            dict(count=1, label="1m", step="month", stepmode="backward"),
            dict(count=6, label="6m", step="month", stepmode="backward"),
            dict(count=1, label="1y", step="year",  stepmode="backward"),
            dict(step="all")
        ]
    ), row=2, col=1)

    fig.update_xaxes(rangeslider=dict(visible=False), row=1, col=1)
    fig.update_xaxes(rangeslider=dict(visible=False), row=1, col=2)
    fig.update_xaxes(rangeslider=dict(visible=False), row=2, col=2)

fig.update_layout(
    title=f"Descomposición STL (period={PERIOD}, robust={ROBUST})",
    height=700, width=1000,
    legend=dict(orientation='h', yanchor='bottom', y=1.02, xanchor='right', x=1)
)

fig.show()

## <a id='toc1_8_'></a>[🎭 Pruebas ACF y PACF](#toc0_)

In [87]:
# =========================
TARGET_COL = 'TipoCambio'
NLAGS      = 40   
ALPHA      = 0.05 
# =========================

In [88]:
df = df_train.copy()
if not isinstance(df.index, pd.DatetimeIndex):
    df.index = pd.to_datetime(df.index, errors='raise')
df = df.sort_index()
y = df[TARGET_COL].astype(float).copy()
if y.isna().any():
    y = y.interpolate(method='time').ffill().bfill()

acf_vals, acf_confint = acf(y, nlags=NLAGS, alpha=ALPHA)
pacf_vals, pacf_confint = pacf(y, nlags=NLAGS, alpha=ALPHA, method='yw')  # <- cambiado
lags = np.arange(len(acf_vals))

In [89]:
fig = make_subplots(rows=1, cols=2, subplot_titles=("ACF", "PACF"))

fig.add_trace(go.Bar(x=lags, y=acf_vals, name='ACF', marker_color='steelblue'),
              row=1, col=1)
fig.add_trace(go.Scatter(x=lags, y=acf_confint[:,0], mode='lines', line=dict(width=0), showlegend=False),
              row=1, col=1)
fig.add_trace(go.Scatter(x=lags, y=acf_confint[:,1], mode='lines', line=dict(width=0),
                         fill='tonexty', fillcolor='rgba(30,144,255,0.2)', showlegend=False),
              row=1, col=1)

fig.add_trace(go.Bar(x=lags, y=pacf_vals, name='PACF', marker_color='indianred'),
              row=1, col=2)
fig.add_trace(go.Scatter(x=lags, y=pacf_confint[:,0], mode='lines', line=dict(width=0), showlegend=False),
              row=1, col=2)
fig.add_trace(go.Scatter(x=lags, y=pacf_confint[:,1], mode='lines', line=dict(width=0),
                         fill='tonexty', fillcolor='rgba(220,20,60,0.2)', showlegend=False),
              row=1, col=2)

fig.update_layout(
    title=f"ACF y PACF (nlags={NLAGS}, alpha={ALPHA})",
    height=500, width=900,
    showlegend=False
)
fig.show()

## <a id='toc1_9_'></a>[💻 Modelado SARIMA](#toc0_)
Aquí se construirá y entrenará el modelo SARIMA utilizando la serie estacionaria.

In [90]:
def run_sarima(df_train, df_test, p, d, q, P, D, Q, m, transform=None):
    """
    Entrena un SARIMA(p,d,q)(P,D,Q,m) sobre df_train y evalúa en df_test.
    transform: None | 'log' | 'boxcox'
    Retorna dict con fit, y_train, y_test, y_pred (todos pd.Series), métricas.
    """
    y_train = df_train['TipoCambio'].astype(float).copy()
    y_test  = df_test['TipoCambio'].astype(float).copy()

    lmbda = None
    if transform == 'log':
        y_train = np.log(y_train)
        y_test  = np.log(y_test)
    elif transform == 'boxcox':
        y_train_vals, lmbda = boxcox(y_train.values)         
        y_train = pd.Series(y_train_vals, index=y_train.index, name=y_train.name)
        y_test_vals = boxcox(y_test.values, lmbda=lmbda)      
        y_test = pd.Series(y_test_vals, index=y_test.index, name=y_test.name)

    model = SARIMAX(
        y_train,
        order=(p, d, q),
        seasonal_order=(P, D, Q, m),
        enforce_stationarity=False,
        enforce_invertibility=False
    )
    fit = model.fit(disp=False)

    fc = fit.get_forecast(steps=len(y_test))
    y_pred = fc.predicted_mean  
    y_pred = pd.Series(y_pred.values, index=y_test.index, name='forecast')

    if transform == 'log':
        y_pred = pd.Series(np.exp(y_pred.values), index=y_pred.index, name=y_pred.name)
        y_test = pd.Series(np.exp(y_test.values), index=y_test.index, name=y_test.name)
        y_train = pd.Series(np.exp(y_train.values), index=y_train.index, name=y_train.name)
    elif transform == 'boxcox':
        y_pred = pd.Series(inv_boxcox(y_pred.values, lmbda), index=y_pred.index, name=y_pred.name)
        y_test = pd.Series(inv_boxcox(y_test.values,  lmbda), index=y_test.index, name=y_test.name)
        y_train = pd.Series(inv_boxcox(y_train.values, lmbda), index=y_train.index, name=y_train.name)

    rmse = float(np.sqrt(mean_squared_error(y_test, y_pred)))
    mae  = float(mean_absolute_error(y_test, y_pred))

    return {
        "fit": fit,
        "y_train": y_train,
        "y_test": y_test,
        "y_pred": y_pred,
        "rmse": rmse,
        "mae": mae,
        "transform": transform
    }

In [91]:
def plot_results_plotly(res, title):
    fig = go.Figure()

    # Serie de entrenamiento
    fig.add_trace(go.Scatter(
        x=res["y_train"].index, y=res["y_train"],
        mode='lines', name='Train'
    ))

    # Serie de test
    fig.add_trace(go.Scatter(
        x=res["y_test"].index, y=res["y_test"],
        mode='lines', name='Test', line=dict(color='black')
    ))

    # Predicciones
    fig.add_trace(go.Scatter(
        x=res["y_test"].index, y=res["y_pred"],
        mode='lines', name='Forecast', line=dict(color='red')
    ))

    fig.update_layout(
        title=f"{title}<br>RMSE={res['rmse']:.2f}, MAE={res['mae']:.2f}",
        xaxis_title="Fecha",
        yaxis_title="Tipo de cambio",
        template="plotly_white",
        height=500,
        width=900,
        legend=dict(orientation='h', yanchor='bottom', y=1.02,
                    xanchor='right', x=1)
    )
    
    fig.show()

In [92]:
p,d,q = 1,1,1
P,D,Q,m = 1,1,1,5  

# 1. Sin transformación
res_raw = run_sarima(df_train, df_test, p,d,q,P,D,Q,m, transform=None)
print("RAW - RMSE:", res_raw["rmse"], "MAE:", res_raw["mae"])

# 2. Con log
res_log = run_sarima(df_train, df_test, p,d,q,P,D,Q,m, transform='log')
print("LOG - RMSE:", res_log["rmse"], "MAE:", res_log["mae"])

# 3. Con Box–Cox
res_boxcox = run_sarima(df_train, df_test, p,d,q,P,D,Q,m, transform='boxcox')
print("BOXCOX - RMSE:", res_boxcox["rmse"], "MAE:", res_boxcox["mae"])

RAW - RMSE: 0.15902672267569878 MAE: 0.12193176968629071
LOG - RMSE: 0.1596973469193792 MAE: 0.12184431712875525
BOXCOX - RMSE: 0.12621237494106144 MAE: 0.10696767344200737

In [93]:
print(df_test)

print(res_raw["y_pred"])

            TipoCambio
Fecha
2025-09-02     18.7072
2025-09-03     18.6873
2025-09-04     18.7577
2025-09-05     18.6792
2025-09-08     18.6550
2025-09-09     18.6353
2025-09-10     18.5920
2025-09-11     18.5287
2025-09-12     18.4757
2025-09-15     18.3635
2025-09-16     18.3635
2025-09-17     18.3257
Fecha
2025-09-02    18.654139
2025-09-03    18.643765
2025-09-04    18.642967
2025-09-05    18.625676
2025-09-08    18.634974
2025-09-09    18.654188
2025-09-10    18.637482
2025-09-11    18.640917
2025-09-12    18.617809
2025-09-15    18.632561
2025-09-16    18.645441
2025-09-17    18.634304
Freq: B, Name: forecast, dtype: float64

In [94]:
# Configura tus parámetros
p,d,q = 1,1,1
P,D,Q,m = 1,1,1,5  # ejemplo; ajusta m según tu frecuencia

res_raw    = run_sarima(df_train, df_test, p,d,q,P,D,Q,m, transform=None)
res_log    = run_sarima(df_train, df_test, p,d,q,P,D,Q,m, transform='log')
res_boxcox = run_sarima(df_train, df_test, p,d,q,P,D,Q,m, transform='boxcox')

plot_results_plotly(res_raw, "SARIMA sin transformación")
plot_results_plotly(res_log, "SARIMA con log")
plot_results_plotly(res_boxcox, "SARIMA con Box–Cox")

In [95]:
def plot_compare_three(res_raw, res_log, res_boxcox, show_rangeslider=True):
    """
    Muestra en una sola figura 3x1:
      - Panel 1: SARIMA sin transformación
      - Panel 2: SARIMA con log
      - Panel 3: SARIMA con Box–Cox
    Cada panel incluye Train, Test y Forecast.
    """

    # Títulos con métricas
    t1 = f"SARIMA sin transformación | RMSE={res_raw['rmse']:.3f}, MAE={res_raw['mae']:.3f}"
    t2 = f"SARIMA con log | RMSE={res_log['rmse']:.3f}, MAE={res_log['mae']:.3f}"
    t3 = f"SARIMA con Box–Cox | RMSE={res_boxcox['rmse']:.3f}, MAE={res_boxcox['mae']:.3f}"

    fig = make_subplots(
        rows=3, cols=1, shared_xaxes=False,
        subplot_titles=(t1, t2, t3),
        vertical_spacing=0.08
    )

    # --- Panel 1: RAW ---
    fig.add_trace(go.Scatter(x=res_raw["y_train"].index, y=res_raw["y_train"], mode='lines', name='Train (raw)'), row=1, col=1)
    fig.add_trace(go.Scatter(x=res_raw["y_test"].index,  y=res_raw["y_test"],  mode='lines', name='Test (raw)'),  row=1, col=1)
    fig.add_trace(go.Scatter(x=res_raw["y_test"].index,  y=res_raw["y_pred"],  mode='lines', name='Forecast (raw)'), row=1, col=1)

    # --- Panel 2: LOG ---
    fig.add_trace(go.Scatter(x=res_log["y_train"].index, y=res_log["y_train"], mode='lines', name='Train (log->nivel)'), row=2, col=1)
    fig.add_trace(go.Scatter(x=res_log["y_test"].index,  y=res_log["y_test"],  mode='lines', name='Test (log->nivel)'),  row=2, col=1)
    fig.add_trace(go.Scatter(x=res_log["y_test"].index,  y=res_log["y_pred"],  mode='lines', name='Forecast (log->nivel)'), row=2, col=1)

    # --- Panel 3: BOXCOX ---
    fig.add_trace(go.Scatter(x=res_boxcox["y_train"].index, y=res_boxcox["y_train"], mode='lines', name='Train (bc->nivel)'), row=3, col=1)
    fig.add_trace(go.Scatter(x=res_boxcox["y_test"].index,  y=res_boxcox["y_test"],  mode='lines', name='Test (bc->nivel)'),  row=3, col=1)
    fig.add_trace(go.Scatter(x=res_boxcox["y_test"].index,  y=res_boxcox["y_pred"],  mode='lines', name='Forecast (bc->nivel)'), row=3, col=1)

    # Sincronizar TODAS las X
    fig.update_xaxes(matches='x')

    # Rangeslider solo en el panel inferior
    if show_rangeslider:
        fig.update_xaxes(rangeslider=dict(visible=True), row=3, col=1)
        fig.update_xaxes(rangeselector=dict(
            buttons=[
                dict(count=1, label="1m", step="month", stepmode="backward"),
                dict(count=6, label="6m", step="month", stepmode="backward"),
                dict(count=1, label="1y", step="year",  stepmode="backward"),
                dict(step="all")
            ]
        ), row=3, col=1)
        # asegurarse de no duplicarlo arriba
        fig.update_xaxes(rangeslider=dict(visible=False), row=1, col=1)
        fig.update_xaxes(rangeslider=dict(visible=False), row=2, col=1)

    fig.update_layout(
        title="Comparación SARIMA por transformación",
        xaxis_title="Fecha",
        yaxis_title="Tipo de cambio",
        template="plotly_white",
        height=900, width=1000,
        legend=dict(orientation='h', yanchor='bottom', y=1.02, xanchor='right', x=1)
    )
    fig.show()

In [96]:
plot_compare_three(res_raw, res_log, res_boxcox, show_rangeslider=True)

## <a id='toc1_10_'></a>[🟰 Metricas](#toc0_)

In [97]:
def calcular_mape(y_true, y_pred):
    """
    Calcula el MAPE (Mean Absolute Percentage Error).
    Valores cercanos a 0 indican un mejor desempeño.
    """
    y_true, y_pred = np.array(y_true), np.array(y_pred)
    return np.mean(np.abs((y_true - y_pred) / y_true)) * 100


def calcular_accuracy(y_true, y_pred):
    """
    Calcula la accuracy como 100 - MAPE.
    Esto es útil para expresar el desempeño como porcentaje de acierto.
    """
    mape = calcular_mape(y_true, y_pred)
    return 100 - mape


def calcular_rmse(y_true, y_pred):
    """
    Calcula el RMSE (Root Mean Squared Error).
    Es sensible a errores grandes porque eleva al cuadrado.
    """
    return np.sqrt(mean_squared_error(y_true, y_pred))


def calcular_smape(y_true, y_pred):
    """
    Calcula el SMAPE (Symmetric Mean Absolute Percentage Error).
    Útil cuando hay valores cercanos a cero.
    """
    y_true, y_pred = np.array(y_true), np.array(y_pred)
    return 100 * np.mean(2 * np.abs(y_pred - y_true) / (np.abs(y_true) + np.abs(y_pred)))

In [98]:
mape_raw = calcular_mape(res_raw['y_test'], res_raw['y_pred'])
accuracy_raw = calcular_accuracy(res_raw['y_test'], res_raw['y_pred'])
rmse_raw = calcular_rmse(res_raw['y_test'], res_raw['y_pred'])
smape_raw = calcular_smape(res_raw['y_test'], res_raw['y_pred'])

mape_log = calcular_mape(res_log['y_test'], res_log['y_pred'])
accuracy_log = calcular_accuracy(res_log['y_test'], res_log['y_pred'])
rmse_log = calcular_rmse(res_log['y_test'], res_log['y_pred'])
smape_log = calcular_smape(res_log['y_test'], res_log['y_pred'])

mape_boxcox = calcular_mape(res_boxcox['y_test'], res_boxcox['y_pred'])
accuracy_boxcox = calcular_accuracy(res_boxcox['y_test'], res_boxcox['y_pred'])
rmse_boxcox = calcular_rmse(res_boxcox['y_test'], res_boxcox['y_pred'])
smape_boxcox = calcular_smape(res_boxcox['y_test'], res_boxcox['y_pred'])

print(' ------ Metricas sin Transformaciones ------')
print(f"MAPE sin trasnsformaciones: {mape_raw:.2f}%")
print(f"Accuracy sin trasnsformaciones: {accuracy_raw:.2f}%")
print(f"RMSE sin trasnsformaciones: {rmse_raw:.2f}")
print(f"SMAPE sin trasnsformaciones: {smape_raw:.2f}%")
print('\n')
print(' ------ Metricas con logaritmica ------')
print(f"MAPE con logaritmica: {mape_log:.2f}%")
print(f"Accuracy con logaritmica: {accuracy_log:.2f}%")
print(f"RMSE con logaritmica: {rmse_log:.2f}")
print(f"SMAPE con logaritmica: {smape_log:.2f}%")
print('\n')
print(' ------ Metricas con boxcox ------')
print(f"MAPE con boxcox: {mape_boxcox:.2f}%")
print(f"Accuracy con boxcox: {accuracy_boxcox:.2f}%")
print(f"RMSE con boxcox: {rmse_boxcox:.2f}")
print(f"SMAPE con boxcox: {smape_boxcox:.2f}%")

 ------ Metricas sin Transformaciones ------
MAPE sin trasnsformaciones: 0.66%
Accuracy sin trasnsformaciones: 99.34%
RMSE sin trasnsformaciones: 0.16
SMAPE sin trasnsformaciones: 0.66%


 ------ Metricas con logaritmica ------
MAPE con logaritmica: 0.66%
Accuracy con logaritmica: 99.34%
RMSE con logaritmica: 0.16
SMAPE con logaritmica: 0.66%


 ------ Metricas con boxcox ------
MAPE con boxcox: 0.58%
Accuracy con boxcox: 99.42%
RMSE con boxcox: 0.13
SMAPE con boxcox: 0.58%

## <a id='toc1_11_'></a>[🎯 Conclusiones](#toc0_)
En esta sección se anotarán las conclusiones del análisis y los resultados del modelo.

In [ ]:
# --- 0) Construir la serie con TODO: train + test ---
# (Si ya tienes df completo con todo el histórico, también vale usar y_all = df['TipoCambio'])
y_all = pd.concat([
    df_train['TipoCambio'],
    df_test['TipoCambio']
]).sort_index()

# Trabajar en frecuencia de días hábiles y rellenar huecos hábiles
y_all = y_all.asfreq('B').ffill()

# --- 1) Ajustar el SARIMA con TODO el histórico ---
p, d, q = 1, 1, 1
P, D, Q, m = 1, 1, 1, 5   # semana hábil

model = SARIMAX(
    y_all.astype(float),
    order=(p, d, q),
    seasonal_order=(P, D, Q, m),
    enforce_stationarity=False,
    enforce_invertibility=False
)
fit_model = model.fit(disp=False)

# --- 2) Rango objetivo ---
start_date = pd.Timestamp('2025-09-22')
end_date   = pd.Timestamp('2025-09-26')
target_idx = pd.bdate_range(start_date, end_date, freq='B')

# --- 3) Predicción puntual 22–26 (in/out-of-sample según corresponda) ---
last_obs = y_all.index[-1]

if target_idx[-1] <= last_obs:
    pred_res = fit_model.get_prediction(start=target_idx[0], end=target_idx[-1])
    mean_pred = pred_res.predicted_mean.reindex(target_idx)
    ci = pred_res.conf_int().reindex(target_idx)
else:
    n_steps = len(pd.bdate_range(last_obs + BDay(1), end_date, freq='B'))
    fc = fit_model.get_forecast(steps=n_steps)
    fc_index = pd.bdate_range(last_obs + BDay(1), periods=n_steps, freq='B')

    mean_pred = pd.Series(fc.predicted_mean.values, index=fc_index, name='Predicción')
    ci = fc.conf_int()
    ci.index = fc_index

    mean_pred = mean_pred.reindex(target_idx)
    ci = ci.reindex(target_idx)

pred_22_26 = pd.DataFrame({
    'Predicción': mean_pred,
    'IC_inf': ci.iloc[:, 0],
    'IC_sup': ci.iloc[:, 1],
})
pred_22_26.index.name = 'Fecha'

# --- 4) Pronóstico CONTINUO desde el día hábil siguiente a last_obs hasta 26-sep (para evitar el “salto”) ---
fc_full_idx = pd.bdate_range(last_obs + BDay(1), end_date, freq='B')
if len(fc_full_idx) > 0:
    fc_full = fit_model.get_forecast(steps=len(fc_full_idx))
    fc_full_mean = pd.Series(fc_full.predicted_mean.values, index=fc_full_idx, name='Forecast continuo')
else:
    fc_full_mean = pd.Series(dtype=float)

# Guardamos también el observado completo para el gráfico
y_observado = y_all.copy()

print("Última fecha observada:", y_observado.index[-1].date())
print("Pronóstico 22–26 Sep:")
print(pred_22_26.round(4))

Última fecha observada: 2025-09-17
Pronóstico 22–26 Sep:
            Predicción   IC_inf   IC_sup
Fecha
2025-09-22     18.3280  17.8817  18.7743
2025-09-23     18.3487  17.8323  18.8652
2025-09-24     18.3329  17.7561  18.9097
2025-09-25     18.3371  17.7115  18.9627
2025-09-26     18.3126  17.6428  18.9824

In [ ]:
# Observado reciente (últimos 90 días hábiles)
y_recent = y_observado.last('90B')

fig = go.Figure()

# Observado
fig.add_trace(go.Scatter(
    x=y_recent.index, y=y_recent.values,
    mode='lines', name='Observado'
))

# Forecast continuo
if not fc_full_mean.empty:
    fig.add_trace(go.Scatter(
        x=fc_full_mean.index, y=fc_full_mean.values,
        mode='lines', name='Pronóstico continuo',
        line=dict(dash='dash')
    ))

# Pronóstico puntual 22–26 (marcadores)
fig.add_trace(go.Scatter(
    x=pred_22_26.index, y=pred_22_26['Predicción'],
    mode='lines+markers', name='Pronóstico 22–26 Sep'
))

# Banda de confianza 95%
fig.add_trace(go.Scatter(
    x=pred_22_26.index.tolist()+pred_22_26.index[::-1].tolist(),
    y=pred_22_26['IC_sup'].tolist()+pred_22_26['IC_inf'][::-1].tolist(),
    fill='toself', mode='lines', line=dict(width=0),
    name='IC 95%'
))

# Enfocar ventana: 90 días antes de la última fecha pronosticada
xmin = pd.Timestamp('2025-09-26') - BDay(90)
xmax = pd.Timestamp('2025-09-26') + BDay(1)

fig.update_layout(
    title="Tipo de cambio FIX — Observado y Pronóstico hasta 26-Sep (frecuencia B)",
    xaxis_title="Fecha",
    yaxis_title="Pesos por USD",
    template="plotly_white",
    height=500, width=900,
    xaxis=dict(range=[xmin, xmax])
)

fig.show()